package com.dec.lite.directory;

public enum DirectoryStage {
    PLANNED, CHECKING_DEPENDENCIES, EXECUTING_ACTIONS, APPLYING_CHANGE,
    VERIFYING_PRODUCE, VERIFYING_INFORMATION, CLASSIFYING, COMPLETED, FAILED, BACK,
    TRANSACTION
}
